version: "3.9"

x-template-common: &common-service
  restart: always
  logging:
    driver: json-file
  networks:
    - net
    
networks:
  net:

services:
  postgres:
    <<: *common-service
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PAS}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "5432:5432"
    shm_size: 2gb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

volumes:
  Volumes: